[package]
name = "chip8"
version = "0.1.0"
authors = ["Evaldas Tyla <Evaldas.Tyla@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = { version = "0.6", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2"
lazy_static = "1.3.0"