[package]
name = "chip8"
version = "0.1.0"
authors = ["Evaldas Tyla <Evaldas.Tyla@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.6"
wasm-bindgen = "0.2"
web-sys = { version = "0.3.5", features = ['console'] }